"""empty message

Revision ID: 17fdf2c9cd06
Revises: c5e8c09b9e29
Create Date: 2025-06-10 12:36:42.684835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fdf2c9cd06'
down_revision = 'c5e8c09b9e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board__category',
    sa.Column('board_category_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('board_category_id'),
    sa.UniqueConstraint('board_category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board__category')
    # ### end Alembic commands ###
