"""empty message

Revision ID: 2be691c18cf8
Revises: 5e021e0d35c8
Create Date: 2025-06-17 22:50:41.533753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be691c18cf8'
down_revision = '5e021e0d35c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_milestone',
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('milestone', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.plant_id'], ),
    sa.PrimaryKeyConstraint('milestone_id'),
    sa.UniqueConstraint('milestone_id')
    )
    op.create_table('growth_milestone_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('log_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['growth_milestone.milestone_id'], ),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('growth_milestone_log')
    op.drop_table('growth_milestone')
    # ### end Alembic commands ###
