"""empty message

Revision ID: 488a4a053b5e
Revises: ddc70b482acc
Create Date: 2025-06-28 22:43:28.040192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488a4a053b5e'
down_revision = 'ddc70b482acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('test_case',
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.PrimaryKeyConstraint('test_case_id'),
    sa.UniqueConstraint('test_case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case')
    op.drop_table('submission')
    # ### end Alembic commands ###
