"""empty message

Revision ID: 5624a9e1cd39
Revises: 5fba97e6dcdf
Create Date: 2025-05-29 14:43:38.712701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5624a9e1cd39'
down_revision = '5fba97e6dcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'rank', ['rank_id'], ['rank_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rank_id')

    # ### end Alembic commands ###
