"""empty message

Revision ID: 5aa7c8780744
Revises: e273d533089f
Create Date: 2025-07-12 21:25:53.648099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aa7c8780744'
down_revision = 'e273d533089f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_login_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('line_bot_user_id', sa.String(length=64), nullable=True))
        batch_op.drop_index('line_user_id')
        batch_op.create_unique_constraint(None, ['line_bot_user_id'])
        batch_op.create_unique_constraint(None, ['line_login_user_id'])
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('line_user_id', ['line_user_id'], unique=False)
        batch_op.drop_column('line_bot_user_id')
        batch_op.drop_column('line_login_user_id')

    # ### end Alembic commands ###
