"""empty message

Revision ID: 5e021e0d35c8
Revises: 94e4b67d0ab2
Create Date: 2025-06-17 12:00:05.176730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e021e0d35c8'
down_revision = '94e4b67d0ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentorship_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentorship_schedule', schema=None) as batch_op:
        batch_op.drop_column('meeting_link')

    # ### end Alembic commands ###
