"""empty message

Revision ID: 5fba97e6dcdf
Revises: 1072df9156c4
Create Date: 2025-05-28 09:49:44.291660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fba97e6dcdf'
down_revision = '1072df9156c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_code', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['category_code'])

    with op.batch_alter_table('user_rank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_code', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rank', schema=None) as batch_op:
        batch_op.drop_column('rank_code')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('category_code')

    # ### end Alembic commands ###
