"""empty message

Revision ID: 65b91b6d8b95
Revises: db0c85b86951
Create Date: 2025-05-14 22:32:13.433174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65b91b6d8b95'
down_revision = 'db0c85b86951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rank',
    sa.Column('user_rank_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rank_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.rank_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_rank_id'),
    sa.UniqueConstraint('user_rank_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('rank_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('user_ibfk_1', 'rank', ['rank_id'], ['rank_id'])

    op.drop_table('user_rank')
    # ### end Alembic commands ###
