"""empty message

Revision ID: 6987c31ac872
Revises: 1f578b46b4d7
Create Date: 2025-06-06 22:54:37.833492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6987c31ac872'
down_revision = '1f578b46b4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorship_request',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('mentee_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('detail', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('actionurl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('actionurl')
        batch_op.drop_column('priority')
        batch_op.drop_column('detail')
        batch_op.drop_column('title')
        batch_op.drop_column('type')

    op.drop_table('mentorship_request')
    # ### end Alembic commands ###
