"""empty message

Revision ID: 850733cb7a00
Revises: cdf3b5589705
Create Date: 2025-06-04 17:06:27.648053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850733cb7a00'
down_revision = 'cdf3b5589705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.drop_column('group_description')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
