"""empty message

Revision ID: 94e4b67d0ab2
Revises: 17fdf2c9cd06
Create Date: 2025-06-17 10:32:07.561268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e4b67d0ab2'
down_revision = '17fdf2c9cd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorship_feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('mentorship_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorship.mentorship_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('mentorship_note',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('mentorship_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('preparation', 'summary', name='note_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorship.mentorship_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('mentorship_schedule',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('mentorship_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'canceled', name='mentorship_status'), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorship.mentorship_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentorship_schedule')
    op.drop_table('mentorship_note')
    op.drop_table('mentorship_feedback')
    # ### end Alembic commands ###
