"""empty message

Revision ID: c5e8c09b9e29
Revises: 6987c31ac872
Create Date: 2025-06-07 22:20:18.580140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e8c09b9e29'
down_revision = '6987c31ac872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('motivation_style', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('motivation_style')
        batch_op.drop_column('size')
        batch_op.drop_column('color')
        batch_op.drop_column('plant_name')

    # ### end Alembic commands ###
