"""empty message

Revision ID: db0c85b86951
Revises: 
Create Date: 2025-05-13 21:55:46.281123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0c85b86951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('rank',
    sa.Column('rank_id', sa.String(length=36), nullable=False),
    sa.Column('rank_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rank_id'),
    sa.UniqueConstraint('rank_id')
    )
    op.create_table('problem',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('problem_id'),
    sa.UniqueConstraint('problem_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('seibetu', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('rank_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.rank_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_table('board',
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('board_id'),
    sa.UniqueConstraint('board_id')
    )
    op.create_table('group_chat',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('group_image', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_table('mentorship',
    sa.Column('mentorship_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('mentee_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('mentorship_id'),
    sa.UniqueConstraint('mentorship_id')
    )
    op.create_table('plant',
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('growth_stage', sa.String(length=255), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('plant_id'),
    sa.UniqueConstraint('plant_id')
    )
    op.create_table('school_info',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('school_type', sa.String(length=50), nullable=False),
    sa.Column('study_line', sa.String(length=255), nullable=False),
    sa.Column('academic_department', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('school_id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('user_category',
    sa.Column('user_category_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_category_id'),
    sa.UniqueConstraint('user_category_id')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('send_user_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_user_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('chat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.group_id'], ),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['send_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id'),
    sa.UniqueConstraint('comment_id')
    )
    op.create_table('group_member',
    sa.Column('group_member_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_member_id'),
    sa.UniqueConstraint('group_member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_member')
    op.drop_table('comment')
    op.drop_table('chats')
    op.drop_table('user_category')
    op.drop_table('school_info')
    op.drop_table('plant')
    op.drop_table('mentorship')
    op.drop_table('group_chat')
    op.drop_table('board')
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('problem')
    op.drop_table('rank')
    op.drop_table('category')
    # ### end Alembic commands ###
