"""empty message

Revision ID: ddc70b482acc
Revises: 2be691c18cf8
Create Date: 2025-06-20 17:15:08.933975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddc70b482acc'
down_revision = '2be691c18cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentorship_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('mentorship_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'group_chat', ['group_id'], ['group_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentorship_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('mentorship_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
