"""empty message

Revision ID: e273d533089f
Revises: a06e1788f688
Create Date: 2025-07-08 11:19:18.142761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e273d533089f'
down_revision = 'a06e1788f688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['line_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###
